#include"core.h"

BITMAP *screenBuffer;
volatile long speed_counter = 0;

//Function needed to limit screen rate
void increment_speed_counter(){
    speed_counter++;
}END_OF_FUNCTION(increment_speed_counter);

//Allegro init fun!
void techInit(){
     allegro_init(); // all Allegro programs need this
     set_color_depth(32);
     set_gfx_mode(GFX_AUTODETECT_WINDOWED, WIDTH, HEIGHT, 0, 0);
     
     srand((unsigned)time(0)); 
     
     screenBuffer = create_bitmap(WIDTH, HEIGHT);
     install_keyboard();
     install_mouse();

     LOCK_VARIABLE(speed_counter);
     LOCK_FUNCTION(increment_speed_counter);
     install_int_ex(increment_speed_counter,BPS_TO_TIMER(120));
     /* add other initializations here*/
}

// Paint all the nice stuff generated by the game cicle to the screen
void updateScreen() {
     blit(screenBuffer, screen, 0, 0, 0, 0, WIDTH, HEIGHT);
}
